In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

from scipy import stats
from matplotlib import pyplot as plt

import openpyxl

In [3]:
df_completo = pd.read_csv('./asylum_seekers.csv')

listaVertices = []

listaVertices = set(df_completo['Country / territory of asylum/residence'].unique().tolist() + df_completo['Origin'].unique().tolist())

print(len(listaVertices))

225

C:\Users\Henrique Martinelli\AppData\Local\Temp\ipykernel_5336\1632023050.py:1: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_completo = pd.read_csv('./asylum_seekers.csv')

In [5]:
df_completo

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5.0,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186.0,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250.0,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273.0,150,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129715,2016,United States of America,Zimbabwe,G / IN,232,NaN,229,16,NaN,*,10,28,435,NaN
129716,2016,United States of America,Zimbabwe,G / EO,142,NaN,12,*,NaN,*,23,31,138,NaN
129717,2016,South Africa,Zimbabwe,G / AR,94,9,NaN,NaN,NaN,NaN,94,94,0,NaN
129718,2016,South Africa,Zimbabwe,G / FI,41238,4124,7964,73,NaN,7869,NaN,7942,41260,NaN
129719,2016,Zambia,Zimbabwe,G / FI,*,*,*,0,NaN,*,*,*,*,*

In [7]:
df_2009_2010 = df_completo.loc[(df_completo['Year'] == 2009) | (df_completo['Year'] == 2010)]
df_2009_2010

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
56860,2009,Pakistan,Afghanistan,U / FA,2535,2535,1178,380,0,122,1022,1524.0,2189,2189
56861,2009,Panama,Afghanistan,G / FI,0,0,4,0,0,0,0,NaN,4,4
56862,2009,Philippines,Afghanistan,G / FI,0,0,2,0,0,0,0,NaN,2,0
56863,2009,Papua New Guinea,Afghanistan,J / FA,1,1,2,2,0,0,1,3.0,0,0
56864,2009,Poland,Afghanistan,G / FI,1,0,14,0,3,4,4,11.0,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71919,2010,Ukraine,Zimbabwe,G / AR,2,1,1,0,0,0,0,NaN,3,3
71920,2010,United States of America,Zimbabwe,G / IN,26,0,106,50,0,11,58,119,15,0
71921,2010,United States of America,Zimbabwe,G / EO,202,0,31,52,0,48,54,154,0,0
71922,2010,South Africa,Zimbabwe,G / FI,0,0,146566,429,0,32750,0,33179,0,0
71923,2010,Zambia,Zimbabwe,G / FA,0,0,2,0,0,2,0,2,0,0